// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0009:Member access should be qualified.", Justification = "<Pending>", Scope = "member", Target = "~P:Quartz.QuartzThread.Priority")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Quartz.Spi.MongoDbJobStore.LockManager.SleepThreshold")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Quartz.Spi.MongoDbJobStore.LockManager.Log")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Quartz.Spi.MongoDbJobStore.LockManager._pendingLocks")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Quartz.Spi.MongoDbJobStore.LockManager._pendingLocksSemaphore")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.LockManager.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0009:Member access should be qualified.", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.LockManager.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.LockManager.AcquireLock(Quartz.Spi.MongoDbJobStore.Models.LockType,System.String)~System.Threading.Tasks.Task{System.IDisposable}")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.LockManager.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.LockManager.LockInstance.#ctor(Quartz.Spi.MongoDbJobStore.LockManager,Quartz.Spi.MongoDbJobStore.Models.LockType,System.String)")]
[assembly: SuppressMessage("Style", "IDE0009:Member access should be qualified.", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.QuartzThread.#ctor")]
[assembly: SuppressMessage("Style", "IDE0027:Use expression body for accessor", Justification = "<Pending>", Scope = "member", Target = "~P:Quartz.QuartzThread.Name")]
[assembly: SuppressMessage("Style", "IDE0027:Use expression body for accessor", Justification = "<Pending>", Scope = "member", Target = "~P:Quartz.QuartzThread.Priority")]
[assembly: SuppressMessage("Style", "IDE0009:Member access should be qualified.", Justification = "<Pending>", Scope = "member", Target = "~P:Quartz.QuartzThread.IsBackground")]
[assembly: SuppressMessage("Style", "IDE0027:Use expression body for accessor", Justification = "<Pending>", Scope = "member", Target = "~P:Quartz.QuartzThread.IsBackground")]
[assembly: SuppressMessage("Design", "CA1044:Properties should not be write only", Justification = "<Pending>", Scope = "member", Target = "~P:Quartz.QuartzThread.IsBackground")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.QuartzThread.#ctor")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Repositories.TriggerRepository")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.TriggerRepository.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.SimpleTrigger")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Repositories.SchedulerRepository")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Repositories.SchedulerRepository")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.Id.SchedulerId")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Repositories.SchedulerRepository")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Repositories.SchedulerRepository")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Repositories.SchedulerRepository")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.Scheduler")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Repositories.SchedulerRepository")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.Id.PausedTriggerGroupId")]
[assembly: SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.MongoDbJobStore")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.MisfireHandler")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.LockManager")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.Lock")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.Id.JobDetailId")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Serializers.JobDataMapSerializer")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.Id.FiredTriggerId")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.CronTrigger")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Repositories.CalendarRepository")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "<Pending>", Scope = "type", Target = "~T:Quartz.Spi.MongoDbJobStore.Models.Id.CalendarId")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.CalendarRepository.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.SchedulerRepository.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.PausedTriggerGroupRepository.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.LockRepository.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.JobDetailRepository.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.FiredTriggerRepository.#ctor(MongoDB.Driver.IMongoDatabase,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Models.JobDetail.GetJobDetail~Quartz.IJobDetail")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Quartz.Spi.MongoDbJobStore.MisfireHandler.Log")]
[assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.TriggerRepository.HasMisfiredTriggers(System.DateTime,System.Int32,System.Collections.Generic.List{Quartz.TriggerKey}@)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.MongoDbJobStore.StoreJobsAndTriggers(System.Collections.Generic.IReadOnlyDictionary{Quartz.IJobDetail,System.Collections.Generic.IReadOnlyCollection{Quartz.ITrigger}},System.Boolean,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.MongoDbJobStore.PauseJob(Quartz.JobKey,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.MongoDbJobStore.PauseTriggerGroupInternal(Quartz.Impl.Matchers.GroupMatcher{Quartz.TriggerKey},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyCollection{System.String}}")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.MongoDbJobStore.RecoverJobsInternal~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.MongoDbJobStore.PauseJobs(Quartz.Impl.Matchers.GroupMatcher{Quartz.JobKey},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.IReadOnlyCollection{System.String}}")]
[assembly: SuppressMessage("Style", "IDE0090:Use 'new(...)'", Justification = "<Pending>", Scope = "member", Target = "~F:Quartz.Spi.MongoDbJobStore.Serializers.JobDataMapSerializer._objectSerializer")]
[assembly: SuppressMessage("Style", "IDE0009:Member access should be qualified.", Justification = "<Pending>", Scope = "member", Target = "~M:Quartz.Spi.MongoDbJobStore.Repositories.LockRepository.EnsureIndex~System.Threading.Tasks.Task")]
